[defaults]
enabled = [
  "user-profile",
  "user-summary",
  "stats",
  "sleep",
  "activities-by-date",
  "activity-detail",
]
disabled = [
  "activity-download",
  "activities",
  "activities-for-date",
]
