"""CLI helper for historic amendments of completed requirements."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from reqflow.catalog import (
    append_log_entry,
    begin_historic_amendment,
    catalog_root,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Reopen a completed requirement for a historic amendment while "
            "preserving catalog workflow guardrails."
        ),
    )
    parser.add_argument(
        "--catalog-root",
        type=Path,
        default=None,
        help="Override auto-detection of the docs/requirements directory.",
    )
    parser.add_argument(
        "--requirement",
        required=True,
        help="Requirement identifier to reopen for amendment.",
    )
    parser.add_argument(
        "--reason",
        required=True,
        help="Why the requirement needs a historic amendment.",
    )
    parser.add_argument(
        "--author",
        default="codex",
        help="Author recorded in the requirements log (default: codex).",
    )
    parser.add_argument(
        "--reference",
        default="implementation",
        help="Reference captured in the change log (default: implementation).",
    )
    parser.add_argument(
        "--summary",
        default=None,
        help="Optional change-log summary; defaults to an autogenerated message.",
    )
    parser.add_argument(
        "--allow-parallel",
        action="store_true",
        help="Override the single-doing guard when another requirement is in progress.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    amendment_reason = args.reason.strip()
    if not amendment_reason:
        parser.error("Provide a non-empty --reason value.")

    try:
        catalog_dir = (
            args.catalog_root
            if args.catalog_root is not None
            else catalog_root(Path.cwd())
        )
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        parser.error(str(exc))
        return 2

    functional_path = catalog_dir / "functional.md"
    if not functional_path.exists():
        parser.error("functional catalog not found; run setup first")
        return 2

    log_path = catalog_dir / "log.md"
    if not log_path.exists():
        parser.error("log.md not found in catalog directory")
        return 2

    try:
        begin_historic_amendment(
            functional_path,
            req_id=args.requirement,
            amendment_reason=amendment_reason,
            allow_parallel=args.allow_parallel,
        )
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    summary = (
        args.summary
        or f"Reopened {args.requirement} for historic amendment: {amendment_reason}"
    )
    append_log_entry(
        log_path,
        req_id=args.requirement,
        change_summary=summary,
        author=args.author,
        reference=args.reference,
    )

    print(
        f"Reopened {args.requirement} for historic amendment in {functional_path}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
