"""CLI for marking functional requirements done."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from reqflow.catalog import (
    append_log_entry,
    catalog_root,
    mark_functional_requirement_done,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Mark a functional requirement as done and update the catalog.",
    )
    parser.add_argument(
        "--catalog-root",
        type=Path,
        default=None,
        help="Override the docs/requirements directory (defaults to auto-detect)",
    )
    parser.add_argument(
        "--author",
        default="codex",
        help="Name used for the change log entry (default: codex)",
    )
    parser.add_argument(
        "--reference",
        default="implementation",
        help="Ticket, prompt, or link recorded in the change log (default: implementation)",
    )
    parser.add_argument(
        "--summary",
        default=None,
        help="Optional change-log summary; defaults to an autogenerated message.",
    )
    parser.add_argument(
        "--id",
        required=True,
        help="Requirement identifier to mark done.",
    )
    parser.add_argument(
        "--reason",
        required=True,
        help="Updated reason describing how the requirement was completed.",
    )
    parser.add_argument(
        "--tests",
        action="append",
        required=True,
        dest="tests",
        help="Verifying test path; repeat the flag for multiple entries.",
    )
    parser.add_argument(
        "--commits",
        action="append",
        default=[],
        help="Commit hash referencing the implementation; repeat as needed.",
    )
    return parser




def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    tests: list[str] = args.tests or []
    if not tests:
        parser.error("Provide at least one --tests value.")

    try:
        catalog_dir = args.catalog_root if args.catalog_root else catalog_root(Path.cwd())
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        parser.error(str(exc))

    catalog_path = catalog_dir / "functional.md"
    if not catalog_path.exists():
        parser.error("functional catalog not found; run setup first")

    log_path = catalog_dir / "log.md"
    if not log_path.exists():
        parser.error("log.md not found in catalog directory")

    commits = [value for value in args.commits if value]
    try:
        closed_amendments = mark_functional_requirement_done(
            catalog_path,
            req_id=args.id,
            reason=args.reason,
            tests=tests,
            commits=commits,
        )
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    summary = args.summary or f"Marked {args.id} done: {args.reason}"
    append_log_entry(
        log_path,
        req_id=args.id,
        change_summary=summary,
        author=args.author,
        reference=args.reference,
    )
    for amendment_id in closed_amendments:
        append_log_entry(
            log_path,
            req_id=amendment_id,
            change_summary=f"Closed amendment {amendment_id} after {args.id}",
            author=args.author,
            reference=args.reference,
        )

    lines = [f"Marked {args.id} done in {catalog_path}"]
    if closed_amendments:
        lines.append("Closed amendments: " + ", ".join(closed_amendments))
    print("\n".join(lines))
    return 0





if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
