"""CLI for marking non-functional requirements done."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

from agentlab.utils.approvals import ApprovalError, validate_approval
from reqflow.catalog import (
    append_log_entry,
    catalog_root,
    mark_non_functional_requirement_done,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Mark a non-functional requirement as done and update the catalog.",
    )
    parser.add_argument(
        "--catalog-root",
        type=Path,
        default=None,
        help="Override auto-detection of the docs/requirements directory.",
    )
    parser.add_argument(
        "--author",
        default="codex",
        help="Author recorded in the requirements log (default: codex).",
    )
    parser.add_argument(
        "--reference",
        default="implementation",
        help="Reference captured in the change log (default: implementation).",
    )
    parser.add_argument(
        "--summary",
        default=None,
        help="Optional change-log summary; defaults to an autogenerated message.",
    )
    parser.add_argument(
        "--id",
        required=True,
        help="Non-functional requirement identifier to mark done.",
    )
    parser.add_argument(
        "--reason",
        required=True,
        help="Updated reason describing how the requirement was completed.",
    )
    parser.add_argument(
        "--tests",
        action="append",
        default=[],
        help="Verifying test paths; repeat the flag for multiple entries.",
    )
    parser.add_argument(
        "--scripts",
        action="append",
        default=[],
        help="Verifying script paths; repeat the flag for multiple entries.",
    )
    parser.add_argument(
        "--monitors",
        action="append",
        default=[],
        help="Monitoring references; repeat the flag for multiple entries.",
    )
    parser.add_argument(
        "--approval-source",
        default=None,
        help="Recorded approver or ticket reference (required when approval enforcement is enabled).",
    )
    parser.add_argument(
        "--override-wait-for-approval",
        action="store_true",
        help="Bypass approval enforcement when an explicit override has been granted.",
    )
    return parser


def _clean(values: Sequence[str]) -> list[str]:
    return [value.strip() for value in values if value and value.strip()]


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    tests = _clean(args.tests)
    scripts = _clean(args.scripts)
    monitors = _clean(args.monitors)
    if not (tests or scripts or monitors):
        parser.error("Provide at least one verifying artifact via --tests/--scripts/--monitors.")

    try:
        catalog_dir = (
            args.catalog_root
            if args.catalog_root is not None
            else catalog_root(Path.cwd())
        )
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        parser.error(str(exc))
        return 2

    try:
        approval_context = validate_approval(
            approval_source=args.approval_source,
            override=args.override_wait_for_approval,
            command_name="mark_done_nonfunctional",
        )
    except ApprovalError as exc:
        parser.error(str(exc))
        return 2

    catalog_path = catalog_dir / "non-functional.md"
    if not catalog_path.exists():
        parser.error("non-functional catalog not found; run setup first")
        return 2

    log_path = catalog_dir / "log.md"
    if not log_path.exists():
        parser.error("log.md not found in catalog directory")
        return 2

    try:
        closed_amendments = mark_non_functional_requirement_done(
            catalog_path,
            req_id=args.id,
            reason=args.reason,
            tests=tests,
            scripts=scripts,
            monitors=monitors,
        )
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    summary = args.summary or f"Marked {args.id} done: {args.reason}"
    if approval_context:
        summary = f"{summary} (approval: {approval_context.label})"
    append_log_entry(
        log_path,
        req_id=args.id,
        change_summary=summary,
        author=args.author,
        reference=args.reference,
    )
    for amendment_id in closed_amendments:
        append_log_entry(
            log_path,
            req_id=amendment_id,
            change_summary=(
                f"Closed amendment {amendment_id} after {args.id}"
            ),
            author=args.author,
            reference=args.reference,
        )

    lines = [f"Marked {args.id} done in {catalog_path}"]
    if approval_context:
        lines.append(f"Approval: {approval_context.label}")
    if closed_amendments:
        lines.append("Closed amendments: " + ", ".join(closed_amendments))
    print("\n".join(lines))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
