"""CLI for promoting requirements into active implementation."""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from difflib import SequenceMatcher
from pathlib import Path
from typing import Iterable

from reqflow.catalog import (
    append_log_entry,
    catalog_root,
    reopen_functional_requirement_for_amendment,
    start_functional_requirement,
)

_TODO_MARKER = "## Todo Requirements"
_DONE_MARKER = "## Done Requirements"
_RETIRED_MARKER = "## Retired Requirements"


@dataclass(slots=True)
class RequirementEntry:
    req_id: str
    title: str | None
    status: str | None
    lines: list[str]


@dataclass(slots=True)
class Collision:
    requirement_id: str
    title: str | None
    similarity: float


_STOPWORDS = {
    "the",
    "and",
    "for",
    "with",
    "that",
    "this",
    "into",
    "from",
    "todo",
    "items",
    "placeholder",
    "medium",
    "status",
    "reason",
    "pending",
    "trace",
    "prompts",
    "tests",
    "none",
    "commits",
    "owner",
    "narrative",
    "acceptance",
    "criteria",
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Promote an approved requirement into implementation, "
            "scanning for potential collisions with done entries."
        ),
    )
    parser.add_argument(
        "--catalog-root",
        type=Path,
        default=None,
        help="Override auto-detection of the docs/requirements directory.",
    )
    parser.add_argument(
        "--requirement",
        required=True,
        help="Requirement identifier to promote to doing.",
    )
    parser.add_argument(
        "--author",
        default="codex",
        help="Author recorded in the requirements log (default: codex).",
    )
    parser.add_argument(
        "--reference",
        default="implementation",
        help="Reference captured in the change log (default: implementation).",
    )
    parser.add_argument(
        "--summary",
        default=None,
        help="Custom change-log summary; defaults to an autogenerated message.",
    )
    parser.add_argument(
        "--acknowledge-collisions",
        action="store_true",
        help="Required when potential collisions are detected.",
    )
    parser.add_argument(
        "--acknowledge-related",
        action="store_true",
        help="Required when related requirements are suggested.",
    )
    parser.add_argument(
        "--reopen-related",
        action="append",
        default=[],
        help="Requirement ID to reopen as an amendment; repeat the flag for multiple IDs.",
    )
    parser.add_argument(
        "--allow-parallel",
        action="store_true",
        help="Override the single-doing guard when multiple requirements must proceed in parallel.",
    )
    parser.add_argument(
        "--collision-threshold",
        type=float,
        default=0.45,
        help="Similarity threshold (0-1) for collision detection (default: 0.45).",
    )
    return parser



def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        catalog_dir = (
            args.catalog_root
            if args.catalog_root is not None
            else catalog_root(Path.cwd())
        )
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        parser.error(str(exc))
        return 2

    functional_path = catalog_dir / "functional.md"
    if not functional_path.exists():
        parser.error("functional catalog not found; run setup first")
        return 2

    log_path = catalog_dir / "log.md"
    if not log_path.exists():
        parser.error("log.md not found in catalog directory")
        return 2

    try:
        todo_entries, done_entries = _load_functional_sections(functional_path)
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    target = _find_entry(todo_entries, args.requirement)
    if target is None:
        done_entry = _find_entry(done_entries, args.requirement)
        if done_entry is not None:
            parser.error(f"Requirement {args.requirement} is already done")
            return 2
        parser.error(f"Requirement {args.requirement} not found in todo section")
        return 2

    status = (target.status or "").lower()
    if status != "todo":
        if status == "doing":
            parser.error(f"Requirement {args.requirement} is already in progress")
        else:
            parser.error(
                f"Requirement {args.requirement} must be todo before starting (current status: {status or 'unknown'})."
            )
        return 2

    collisions = _find_collisions(target, done_entries, args.collision_threshold)
    collision_ids = {item.requirement_id for item in collisions}
    if collisions and not args.acknowledge_collisions:
        _print_collision_alert(collisions, args.requirement)
        return 1

    other_entries = [
        entry
        for entry in todo_entries + done_entries
        if entry.req_id != args.requirement
    ]
    related_candidates = _find_related_requirements(
        target,
        other_entries,
        excluded_ids=collision_ids,
    )
    related_ids = [item.requirement_id for item in related_candidates]
    related_acknowledged = args.acknowledge_related or bool(args.reopen_related)
    if related_ids and not related_acknowledged:
        _print_related_alert(related_candidates, args.requirement)
        return 1

    try:
        start_functional_requirement(
            functional_path,
            args.requirement,
            allow_parallel=args.allow_parallel,
        )
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    reopened: list[str] = []
    reopened_collisions: list[str] = []
    for collision in collisions:
        try:
            reopen_functional_requirement_for_amendment(
                functional_path,
                collision.requirement_id,
                args.requirement,
            )
            reopened.append(collision.requirement_id)
            reopened_collisions.append(collision.requirement_id)
        except ValueError as exc:
            parser.error(str(exc))
            return 2

    related_map = {item.requirement_id: item for item in related_candidates}
    reopen_requested = list(dict.fromkeys(args.reopen_related))
    reopened_related: list[str] = []
    for req_id in reopen_requested:
        if req_id in reopened:
            continue
        if req_id not in related_map and req_id not in collision_ids:
            parser.error(
                f"Requirement {req_id} was not among the suggested related items."
            )
            return 2
        try:
            reopen_functional_requirement_for_amendment(
                functional_path,
                req_id,
                args.requirement,
            )
            reopened.append(req_id)
            if req_id in related_map:
                reopened_related.append(req_id)
            else:
                reopened_collisions.append(req_id)
        except ValueError as exc:
            parser.error(str(exc))
            return 2

    collision_note = (
        f"; collisions: {', '.join(c.requirement_id for c in collisions)}"
        if collisions
        else ""
    )
    related_note = (
        f"; related: {', '.join(related_ids)}"
        if related_ids
        else ""
    )
    summary = (
        args.summary
        or f"Started implementation for {args.requirement}{collision_note}{related_note}"
    )
    append_log_entry(
        log_path,
        req_id=args.requirement,
        change_summary=summary,
        author=args.author,
        reference=args.reference,
    )
    for amendment_id in reopened:
        append_log_entry(
            log_path,
            req_id=amendment_id,
            change_summary=(
                f"Reopened {amendment_id} under {args.requirement} for amendment"
            ),
            author=args.author,
            reference=args.reference,
        )

    message = [
        f"Promoted {args.requirement} to doing in {functional_path}",
    ]
    if collisions:
        details = ", ".join(
            f"{item.requirement_id} ({item.title or 'untitled'})"
            for item in collisions
        )
        message.append(f"Potential amendments detected: {details}.")
        if reopened_collisions:
            message.append(
                "Reopened collision amendments: "
                f"{', '.join(reopened_collisions)} (status set to doing with Amends markers)."
            )
    else:
        message.append("No collisions detected.")

    if related_ids:
        if reopened_related:
            message.append(
                "Reopened related amendments: "
                f"{', '.join(reopened_related)} (status set to doing with Amends markers)."
            )
        else:
            message.append(
                "Related requirements suggested: "
                f"{', '.join(related_ids)}."
            )
    else:
        message.append("No related requirements suggested.")

    print("\n".join(message))
    return 0




def _load_functional_sections(path: Path) -> tuple[list[RequirementEntry], list[RequirementEntry]]:
    text = path.read_text(encoding="utf-8")

    before_todo, todo_header, remainder = text.partition(_TODO_MARKER)
    if not todo_header:
        raise ValueError("Functional catalog missing todo section")

    todo_section, done_header, remainder = remainder.partition(_DONE_MARKER)
    if not done_header:
        raise ValueError("Functional catalog missing done section")

    done_section, retired_header, _suffix = remainder.partition(_RETIRED_MARKER)
    if not retired_header:
        raise ValueError("Functional catalog missing retired section")

    return (
        _entries_from_section(todo_section),
        _entries_from_section(done_section),
    )


def _entries_from_section(section_text: str) -> list[RequirementEntry]:
    entries: list[RequirementEntry] = []
    for lines in _split_entries(section_text):
        entry = _parse_entry(lines)
        if entry is not None:
            entries.append(entry)
    return entries


def _split_entries(section: str) -> list[list[str]]:
    lines = section.strip("\n").splitlines()
    entries: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        if line.strip():
            current.append(line)
        elif current:
            entries.append(current)
            current = []
    if current:
        entries.append(current)
    return entries


def _parse_entry(lines: Iterable[str]) -> RequirementEntry | None:
    req_id: str | None = None
    title: str | None = None
    status: str | None = None
    collected: list[str] = []
    for line in lines:
        collected.append(line)
        stripped = line.strip()
        if stripped.startswith("### "):
            heading = stripped[4:]
            req_id_part, _, title_part = heading.partition(":")
            req_id = req_id_part.strip()
            title_candidate = title_part.strip()
            title = title_candidate or title
        elif stripped.startswith("- ID:") and not req_id:
            req_id = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("- Title:") and not title:
            title = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("- Status:"):
            status = stripped.split(":", 1)[1].strip()
    if not req_id:
        return None
    return RequirementEntry(req_id=req_id, title=title, status=status, lines=list(collected))


def _find_entry(entries: Iterable[RequirementEntry], req_id: str) -> RequirementEntry | None:
    for entry in entries:
        if entry.req_id == req_id:
            return entry
    return None


def _find_collisions(
    target: RequirementEntry,
    done_entries: Iterable[RequirementEntry],
    threshold: float,
) -> list[Collision]:
    threshold = max(0.0, min(threshold, 1.0))
    target_text = "\n".join(target.lines)
    collisions: list[Collision] = []
    for entry in done_entries:
        candidate_text = "\n".join(entry.lines)
        similarity = SequenceMatcher(None, target_text, candidate_text).ratio()
        if similarity >= threshold:
            collisions.append(
                Collision(
                    requirement_id=entry.req_id,
                    title=entry.title,
                    similarity=similarity,
                )
            )
    collisions.sort(key=lambda item: item.similarity, reverse=True)
    return collisions


def _extract_tokens(entry: RequirementEntry) -> set[str]:
    tokens: set[str] = set()
    for line in entry.lines:
        for token in re.findall(r"[a-z0-9]{3,}", line.lower()):
            if token not in _STOPWORDS:
                tokens.add(token)
    return tokens


def _find_related_requirements(
    target: RequirementEntry,
    entries: Iterable[RequirementEntry],
    excluded_ids: set[str] | None = None,
    threshold: float = 0.35,
    limit: int = 5,
) -> list[Collision]:
    threshold = max(0.0, min(threshold, 1.0))
    excluded = set(excluded_ids or set())
    target_text = "\n".join(target.lines)
    target_tokens = _extract_tokens(target)
    related: list[Collision] = []
    for entry in entries:
        if entry.req_id in excluded:
            continue
        status = (entry.status or "").lower()
        if status and status != "todo":
            continue
        candidate_text = "\n".join(entry.lines)
        similarity = SequenceMatcher(None, target_text, candidate_text).ratio()
        tokens = _extract_tokens(entry)
        overlap = target_tokens & tokens
        union = target_tokens | tokens
        token_score = (len(overlap) / len(union)) if union else 0.0
        score = max(similarity, token_score)
        if similarity >= threshold or len(overlap) >= 2 or token_score >= 0.2:
            related.append(
                Collision(
                    requirement_id=entry.req_id,
                    title=entry.title,
                    similarity=score,
                )
            )
    related.sort(key=lambda item: item.similarity, reverse=True)
    if limit:
        return related[:limit]
    return related


def _print_collision_alert(collisions: list[Collision], req_id: str) -> None:
    print(
        "Potential catalog collisions detected for "
        f"{req_id}. Review the entries below:",
        file=sys.stderr,
    )
    for collision in collisions:
        title = collision.title or "untitled"
        similarity = f"{collision.similarity:.2f}"
        print(
            f"- {collision.requirement_id} ({title}) similarity={similarity}",
            file=sys.stderr,
        )
    print(
        "Re-run the command with --acknowledge-collisions once you are ready. "
        "Amends lines will be added automatically in later workflow steps.",
        file=sys.stderr,
    )


def _print_related_alert(related: list[Collision], req_id: str) -> None:
    print(
        "Potential related requirements detected for "
        f"{req_id}. Review the entries below:",
        file=sys.stderr,
    )
    for item in related:
        title = item.title or "untitled"
        similarity = f"{item.similarity:.2f}"
        print(
            f"- {item.requirement_id} ({title}) similarity={similarity}",
            file=sys.stderr,
        )
    print(
        "Re-run the command with --acknowledge-related and optionally "
        "--reopen-related <ID> to proceed.",
        file=sys.stderr,
    )


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
