"""CLI for promoting requirements into active implementation."""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from difflib import SequenceMatcher
from pathlib import Path
from typing import Iterable

from reqflow.catalog import (
    append_log_entry,
    catalog_root,
    start_functional_requirement,
)

_TODO_MARKER = "## Todo Requirements"
_DONE_MARKER = "## Done Requirements"
_RETIRED_MARKER = "## Retired Requirements"


@dataclass(slots=True)
class RequirementEntry:
    req_id: str
    title: str | None
    status: str | None
    lines: list[str]


@dataclass(slots=True)
class Collision:
    requirement_id: str
    title: str | None
    similarity: float


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Promote an approved requirement into implementation, "
            "scanning for potential collisions with done entries."
        ),
    )
    parser.add_argument(
        "--catalog-root",
        type=Path,
        default=None,
        help="Override auto-detection of the docs/requirements directory.",
    )
    parser.add_argument(
        "--requirement",
        required=True,
        help="Requirement identifier to promote to doing.",
    )
    parser.add_argument(
        "--author",
        default="codex",
        help="Author recorded in the requirements log (default: codex).",
    )
    parser.add_argument(
        "--reference",
        default="implementation",
        help="Reference captured in the change log (default: implementation).",
    )
    parser.add_argument(
        "--summary",
        default=None,
        help="Custom change-log summary; defaults to an autogenerated message.",
    )
    parser.add_argument(
        "--acknowledge-collisions",
        action="store_true",
        help="Required when potential collisions are detected.",
    )
    parser.add_argument(
        "--collision-threshold",
        type=float,
        default=0.45,
        help="Similarity threshold (0-1) for collision detection (default: 0.45).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        catalog_dir = (
            args.catalog_root
            if args.catalog_root is not None
            else catalog_root(Path.cwd())
        )
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        parser.error(str(exc))
        return 2

    functional_path = catalog_dir / "functional.md"
    if not functional_path.exists():
        parser.error("functional catalog not found; run setup first")
        return 2

    log_path = catalog_dir / "log.md"
    if not log_path.exists():
        parser.error("log.md not found in catalog directory")
        return 2

    try:
        todo_entries, done_entries = _load_functional_sections(functional_path)
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    target = _find_entry(todo_entries, args.requirement)
    if target is None:
        done_entry = _find_entry(done_entries, args.requirement)
        if done_entry is not None:
            parser.error(f"Requirement {args.requirement} is already done")
            return 2
        parser.error(f"Requirement {args.requirement} not found in todo section")
        return 2

    status = (target.status or "").lower()
    if status != "todo":
        if status == "doing":
            parser.error(f"Requirement {args.requirement} is already in progress")
        else:
            parser.error(
                f"Requirement {args.requirement} must be todo before starting (current status: {status or 'unknown'})."
            )
        return 2

    collisions = _find_collisions(target, done_entries, args.collision_threshold)
    if collisions and not args.acknowledge_collisions:
        _print_collision_alert(collisions, args.requirement)
        return 1

    try:
        start_functional_requirement(functional_path, args.requirement)
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    collision_note = (
        f"; collisions: {', '.join(c.requirement_id for c in collisions)}"
        if collisions
        else ""
    )
    summary = (
        args.summary
        or f"Started implementation for {args.requirement}{collision_note}"
    )
    append_log_entry(
        log_path,
        req_id=args.requirement,
        change_summary=summary,
        author=args.author,
        reference=args.reference,
    )

    message = [
        f"Promoted {args.requirement} to doing in {functional_path}",
    ]
    if collisions:
        details = ", ".join(
            f"{item.requirement_id} ({item.title or 'untitled'})"
            for item in collisions
        )
        message.append(
            "Potential amendments detected: "
            f"{details}. Future steps will add Amends lines automatically."
        )
    else:
        message.append("No collisions detected.")
    print("\n".join(message))
    return 0


def _load_functional_sections(path: Path) -> tuple[list[RequirementEntry], list[RequirementEntry]]:
    text = path.read_text(encoding="utf-8")

    before_todo, todo_header, remainder = text.partition(_TODO_MARKER)
    if not todo_header:
        raise ValueError("Functional catalog missing todo section")

    todo_section, done_header, remainder = remainder.partition(_DONE_MARKER)
    if not done_header:
        raise ValueError("Functional catalog missing done section")

    done_section, retired_header, _suffix = remainder.partition(_RETIRED_MARKER)
    if not retired_header:
        raise ValueError("Functional catalog missing retired section")

    return (
        _entries_from_section(todo_section),
        _entries_from_section(done_section),
    )


def _entries_from_section(section_text: str) -> list[RequirementEntry]:
    entries: list[RequirementEntry] = []
    for lines in _split_entries(section_text):
        entry = _parse_entry(lines)
        if entry is not None:
            entries.append(entry)
    return entries


def _split_entries(section: str) -> list[list[str]]:
    lines = section.strip("\n").splitlines()
    entries: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        if line.strip():
            current.append(line)
        elif current:
            entries.append(current)
            current = []
    if current:
        entries.append(current)
    return entries


def _parse_entry(lines: Iterable[str]) -> RequirementEntry | None:
    req_id: str | None = None
    title: str | None = None
    status: str | None = None
    collected: list[str] = []
    for line in lines:
        collected.append(line)
        stripped = line.strip()
        if stripped.startswith("### "):
            heading = stripped[4:]
            req_id_part, _, title_part = heading.partition(":")
            req_id = req_id_part.strip()
            title_candidate = title_part.strip()
            title = title_candidate or title
        elif stripped.startswith("- ID:") and not req_id:
            req_id = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("- Title:") and not title:
            title = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("- Status:"):
            status = stripped.split(":", 1)[1].strip()
    if not req_id:
        return None
    return RequirementEntry(req_id=req_id, title=title, status=status, lines=list(collected))


def _find_entry(entries: Iterable[RequirementEntry], req_id: str) -> RequirementEntry | None:
    for entry in entries:
        if entry.req_id == req_id:
            return entry
    return None


def _find_collisions(
    target: RequirementEntry,
    done_entries: Iterable[RequirementEntry],
    threshold: float,
) -> list[Collision]:
    threshold = max(0.0, min(threshold, 1.0))
    target_text = "\n".join(target.lines)
    collisions: list[Collision] = []
    for entry in done_entries:
        candidate_text = "\n".join(entry.lines)
        similarity = SequenceMatcher(None, target_text, candidate_text).ratio()
        if similarity >= threshold:
            collisions.append(
                Collision(
                    requirement_id=entry.req_id,
                    title=entry.title,
                    similarity=similarity,
                )
            )
    collisions.sort(key=lambda item: item.similarity, reverse=True)
    return collisions


def _print_collision_alert(collisions: list[Collision], req_id: str) -> None:
    print(
        "Potential catalog collisions detected for "
        f"{req_id}. Review the entries below:",
        file=sys.stderr,
    )
    for collision in collisions:
        title = collision.title or "untitled"
        similarity = f"{collision.similarity:.2f}"
        print(
            f"- {collision.requirement_id} ({title}) similarity={similarity}",
            file=sys.stderr,
        )
    print(
        "Re-run the command with --acknowledge-collisions once you are ready. "
        "Amends lines will be added automatically in later workflow steps.",
        file=sys.stderr,
    )


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
