"""CLI for promoting non-functional requirements into active implementation."""
from __future__ import annotations

import argparse
from pathlib import Path

from reqflow.catalog import (
    append_log_entry,
    catalog_root,
    start_non_functional_requirement,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Promote a non-functional requirement into implementation with WIP guard checks.",
    )
    parser.add_argument(
        "--catalog-root",
        type=Path,
        default=None,
        help="Override auto-detection of the docs/requirements directory.",
    )
    parser.add_argument(
        "--requirement",
        required=True,
        help="Non-functional requirement identifier to promote to doing.",
    )
    parser.add_argument(
        "--author",
        default="codex",
        help="Author recorded in the requirements log (default: codex).",
    )
    parser.add_argument(
        "--reference",
        default="implementation",
        help="Reference captured in the change log (default: implementation).",
    )
    parser.add_argument(
        "--summary",
        default=None,
        help="Custom change-log summary; defaults to an autogenerated message.",
    )
    parser.add_argument(
        "--allow-parallel",
        action="store_true",
        help="Override the single-doing guard when multiple non-functional requirements must proceed in parallel.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        catalog_dir = (
            args.catalog_root
            if args.catalog_root is not None
            else catalog_root(Path.cwd())
        )
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        parser.error(str(exc))
        return 2

    non_functional_path = catalog_dir / "non-functional.md"
    if not non_functional_path.exists():
        parser.error("non-functional catalog not found; run setup first")
        return 2

    log_path = catalog_dir / "log.md"
    if not log_path.exists():
        parser.error("log.md not found in catalog directory")
        return 2

    try:
        start_non_functional_requirement(
            non_functional_path,
            args.requirement,
            allow_parallel=args.allow_parallel,
        )
    except ValueError as exc:
        parser.error(str(exc))
        return 2

    summary = (
        args.summary
        or f"Started non-functional implementation for {args.requirement}"
    )
    append_log_entry(
        log_path,
        req_id=args.requirement,
        change_summary=summary,
        author=args.author,
        reference=args.reference,
    )

    print(
        f"Promoted {args.requirement} to doing in {non_functional_path}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
